FROM php:8.3-fpm-alpine3.23 

# Install system dependencies
RUN apk add --no-cache \
bash \
curl \
libpng-dev \
libzip-dev \
zlib-dev

# Install PHP extensions
RUN docker-php-ext-install gd \
&& docker-php-ext-install zip

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install node and npm
RUN apk add --no-cache nodejs npm

WORKDIR /var/www

EXPOSE 9000

